name: property-harvester
services:
  - name: harvester-worker
    github:
      repo: YOUR_GITHUB_USERNAME/YOUR_REPO_NAME
      branch: main
      deploy_on_push: true
    source_dir: /
    run_command: python production_harvester.py
    environment_slug: python
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: HEADLESS
        value: "true"
      - key: MAX_CLICKS
        value: "200"
      - key: START_URL
        value: "https://www.thinkspain.com/property-for-sale"
      - key: OUTPUT_FILE
        value: "harvested_properties.json"
      - key: PROGRESS_FILE
        value: "scraper_progress.json"
      - key: LOG_FILE
        value: "production_scraper.log"
      - key: ERROR_SCREENSHOT_DIR
        value: "error_screenshots"
      - key: MAX_RUNTIME_HOURS
        value: "12"

